### ISSUE TITLE
Why were all the base styles removed?

### ISSUE THREAD

**Issue by shanecarmody** [basscss/basscss-sass#14]
I upgraded from 3.0.0 to 4.0.0 and noticed that there are no longer files which overwrite user-agent styles e.g. `_base-reset.scss`, `_base-typography.scss`, etc. I would love to get some insight into why these were removed, can you let me know :v: or else point me in the direction of the changelog :point_right:

**Comment by jxnblk** [comment]
See https://github.com/basscss/basscss/releases/tag/8.0.0

**Comment by shanecarmody** [comment]
Thanks :+1:
