### ISSUE TITLE
_base-typography.scss: $space-2 is used before it's defined

### ISSUE THREAD

**Issue by firedev** [basscss/basscss-sass#2]
Here is an issue after conversion:

https://github.com/basscss/basscss-sass/blob/master/_base-typography.scss#L13

**Comment by jxnblk** [comment]
What is the issue with this?

**Comment by firedev** [comment]
Is can't be used. Undefined veritable. I edited the file and put `$space` block on top then it went through.

**Comment by jxnblk** [comment]
Are you including the defaults file before this one?

**Comment by firedev** [comment]
I include some, but that's not the point. This one has all the variables it needs just the order is not correct.

**Comment by jxnblk** [comment]
Ah, got it. Thanks for explaining.
