### ISSUE TITLE
http://basscss.com is down.

### ISSUE THREAD

**Issue by bhardin** [basscss/basscss-sass#9]
![screenshot 2016-01-21 12 23 33](https://cloud.githubusercontent.com/assets/172843/12493427/d511aaba-c039-11e5-9069-8bd957fee7b6.png)

**Comment by jxnblk** [comment]
Seems to work for me. Can you verify if it's still down?

**Comment by johno** [comment]
I believe this was the result of a GitHub Pages hiccup that occurred yesterday.
